import '@fontsource/syne/600.css'
import '@fontsource/syne/700.css'
import '@fontsource/nunito/400.css'
import '@fontsource/nunito/600.css'
import '@fontsource/nunito/700.css'
import './styles/main.scss'